Пользуясь только python и Numpy посчитайте значения logloss и кросс-энтропии для мультилейбл и мультиклассовой классификации. Суммируйте значения функции ошибки для разных объектов.

На вход программе подаются nn и kk – количество ответов и классов. Следующие 2n2n задают yy и значения последнего слоя до активации ZZ.

Sample Input 1:

2 2

1 0

0 1

-3.0 2.0

0.0 1.0

Sample Output 1:

6.182 5.32

In [ ]:
import numpy as np        

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def softmax1(z):
    e_x = np.exp(z - np.max(z))
    return e_x / e_x.sum(axis=0)

def softmax(x):
    return(np.exp(x)/np.sum(np.exp(x), axis=1, keepdims=True))

def logloss(y, y_hat):
    y_hat = sigmoid(y_hat)
    loss = -np.sum(y*(np.log(y_hat)) + (1-y)*np.log(1-y_hat))
    return loss

def cross_entropy_loss(y, y_hat):
 #   y_hat = softmax(y_hat)
    return -np.sum(y*np.log(y_hat))

def solution():
    n, k = map(int, input().split())
    y = np.array([list(map(int, input().split())) for _ in range(n)])
    z = np.array([list(map(float, input().split())) for _ in range(n)])

    logloss_value = logloss(y, z)
    crossentropy_value = cross_entropy_loss(y, softmax(z))

    logloss_value = str(np.round(logloss_value, 3))
    crossentropy_value = str(np.round(crossentropy_value, 3))
    print(logloss_value + ' ' + crossentropy_value)

solution()

2 2
1 0
0 1
-3 2
0 1
6.182 5.32


**Всякие тестики на эту тему**

In [ ]:
import torch
import numpy as np

In [ ]:
def sig(x):
 return 1/(1 + np.exp(-x))

In [ ]:
x1 = [0.333, 0.5, 5.0]
x2 = [0.666, 0.25, 10]
x3 = [0.999, 0.1, 1]
x4 = [0.1, 0.1, 0.2]
w1 = np.array([[-0.5, -0.5], [0., 1.], [1.5, 3.0]])
w2 = np.array([[2.5, 0.5, -1.5], [3.5, 1.5, 1.5]])
b1 = [0., 0.]
b2 = [0., 0., 0.]
#a = sigmoida(z1)
y=[1,2,0,1]

In [ ]:
x = np.array([x1, x2, x3, x4])

xw1 = x@w1
print(xw1)
print("sigmoid(xw1) =", sig(xw1))
print(x@w1@w2)

[[ 7.3335 15.3335]
 [14.667  29.917 ]
 [ 1.0005  2.6005]
 [ 0.25    0.65  ]]
sigmoid(xw1) = [[0.99934714 0.99999978]
 [0.99999957 1.        ]
 [0.73115687 0.93089375]
 [0.5621765  0.65701046]]
[[ 72.001  26.667  12.   ]
 [141.377  52.209  22.875]
 [ 11.603   4.401   2.4  ]
 [  2.9     1.1     0.6  ]]


In [ ]:

loss = torch.nn.CrossEntropyLoss(reduction='mean')


>>> output = loss(input, target)
>>> output.backward()

In [ ]:
a = np.array([1, 0, 3])@np.array([[1], [2], [3]]) - 10
print(a)
sig(a)

[0]


array([0.5])

In [ ]:
X = torch.tensor([[0.333, 0.5, 5.0], [0.666, 0.25, 10.0],
                  [0.999, 0.1, 1.0], [0.1, 0.1, 0.2]], requires_grad=False)
W1 = torch.tensor([[-1.5, 0, 1.5],[-0.5, 1., 3.0]], requires_grad=True)
b1 = torch.tensor([[0.,0.]], requires_grad=True)
W2 = torch.tensor([[2.5, 3.5],[0.5, 1.5], [-1.5, 1.5]], requires_grad=True)
b2 = torch.tensor([[0., 0., 0.]], requires_grad=True)
y = torch.tensor([1 ,2, 0,1 ])

a1 = torch.sigmoid(X @ W1.T + b1) 
z2 = (a1 @ W2.T + b2)
CrossEntropyLossCrossEntropyLoss = torch.nn.CrossEntropyLoss( reduction='mean')
loss = CrossEntropyLossCrossEntropyLoss(z2, y)
loss.backward()
print("loss", loss)
print(b1.grad)
print("suM", loss + b1.grad[0])

loss tensor(3.1549, grad_fn=<NllLossBackward0>)
tensor([[0.0962, 0.0980]])
suM tensor([3.2510, 3.2529], grad_fn=<AddBackward0>)
