## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)

In [ ]:
import random

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
b = a.reshape(5, 1)
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
c = np.zeros(10*2)
c.reshape(10, 2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
d = np.zeros(3*6*2)
d.reshape(3, 6, 2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
e = np.zeros(4*3*2*1)
e.reshape(4, 3, 2, 1)

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [ ]:
np.ones(5).astype(int)


array([1, 1, 1, 1, 1])

In [ ]:
np.ones((5, 1)).astype(int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
np.ones((10, 2)).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.ones((3, 6, 2)).astype(int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
np.ones((4, 3, 2, 1)).astype(int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в
* 2 произвольных компоненты
* 3 произвольных компоненты
* 4 произвольных компоненты

In [ ]:

a = np.ones(5)
number = random.randint(1, 5) 
a.reshape(-1, number)

ValueError: ignored

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [ ]:
v = np.random.randint(0, 9, size=(5, 7))
print(v)
print(v[1].max(), v[0].max(), v.sum(), v[0].sum()/5, v[1].sum()/5)

[[0 1 7 7 5 4 5]
 [8 8 6 4 1 8 0]
 [0 8 4 4 6 5 5]
 [8 6 8 6 0 6 2]
 [2 1 6 8 5 4 6]]
8 7 164 5.8 7.0


Задание 6.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [ ]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 7.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [ ]:
print(v[v > 5], "  Все числа больше 5 \n")
print(v[v < 7], "     Все числа меньше 7\n") #это в обычном порядке
print(v[v < 7][::-1], "     Все числа меньше 7 в обратном порядке \n") #а вот это в обратном порядке =)
print(v[(v > 3) & (v % 4 == 0)], "      Все числа больше 3, которые делятся на 4 без остатка \n")
print(v[v % 5 == 3], "   Все числа, остаток от деления на 5 которых равен 3 \n")
print(v.argmax(), "      Индекс максимума\n")
print(v.argmin(), "      Индекс минимума\n")
print(v.argsort(), "     Cписок с индексами элементов отсортированного массива в исходном\n")


[7 7 8 8 6 8 8 6 8 6 8 6 6 6 8 6]   Все числа больше 5 

[0 1 5 4 5 6 4 1 0 0 4 4 6 5 5 6 6 0 6 2 2 1 6 5 4 6]      Все числа меньше 7

[6 4 5 6 1 2 2 6 0 6 6 5 5 6 4 4 0 0 1 4 6 5 4 5 1 0]      Все числа меньше 7 в обратном порядке 

[4 8 8 4 8 8 4 4 8 8 8 4]       Все числа больше 3, которые делятся на 4 без остатка 

[8 8 8 8 8 8 8]    Все числа, остаток от деления на 5 которых равен 3 

7       Индекс максимума

0       Индекс минимума

[[0 1 5 4 6 2 3]
 [6 4 3 2 0 1 5]
 [0 2 3 5 6 4 1]
 [4 6 1 3 5 0 2]
 [1 0 5 4 2 6 3]]      Cписок с индексами элементов отсортированного массива в исходном



Задание 8.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [ ]:
w = np.random.randint(0, 9, size=(5, 7))
print(w, "                                         <====== сам вектор\n")
print(w*3, "                                       <===== умножили на 3\n")
print(w/7, "                                                         <===== поделили на 7\n")
print(w**(2/3), "                                                    <===== возвели в степень 2/3 \n")
print(np.sin(w), "                                                   <===== взяли синус \n")
print(np.log(w), "                                                   <===== взяли log \n")

[[5 1 7 5 6 4 4]
 [6 7 7 4 1 3 1]
 [3 0 5 8 5 7 1]
 [8 6 1 2 4 4 7]
 [4 7 6 6 4 1 6]]                                          <====== сам вектор

[[15  3 21 15 18 12 12]
 [18 21 21 12  3  9  3]
 [ 9  0 15 24 15 21  3]
 [24 18  3  6 12 12 21]
 [12 21 18 18 12  3 18]]                                        <===== умножили на 3

[[0.71428571 0.14285714 1.         0.71428571 0.85714286 0.57142857
  0.57142857]
 [0.85714286 1.         1.         0.57142857 0.14285714 0.42857143
  0.14285714]
 [0.42857143 0.         0.71428571 1.14285714 0.71428571 1.
  0.14285714]
 [1.14285714 0.85714286 0.14285714 0.28571429 0.57142857 0.57142857
  1.        ]
 [0.57142857 1.         0.85714286 0.85714286 0.57142857 0.14285714
  0.85714286]]                                                          <===== поделили на 7

[[2.92401774 1.         3.65930571 2.92401774 3.30192725 2.5198421
  2.5198421 ]
 [3.30192725 3.65930571 3.65930571 2.5198421  1.         2.08008382
  1.        ]
 [2.08008382 0.         2.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


### Разные инициализации + индексирование (3 балла)

Задание 9.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [ ]:
a = np.arange(1, 18, 2)
a.reshape(3, 3)


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 10.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [ ]:
a = np.arange(32, 0, -2)
a.reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 11.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [ ]:
a = [[(k/10, j/10) for k in range(-5, 5)] for j in range(-5, 5)]
#print(len(a), len(a[0])) #просто проверяю размерность, тк вывод какой-то кривой...


a = np.arange(-0.5, 0.6, 0.1)
b = np.arange(-0.5, 0.6, 0.1)
b.reshape(11, 1)

ans = np.meshgrid(a, b)
np.dstack((ans[0], ans[1]))

array([[[-0.5, -0.5],
        [-0.4, -0.5],
        [-0.3, -0.5],
        [-0.2, -0.5],
        [-0.1, -0.5],
        [-0. , -0.5],
        [ 0.1, -0.5],
        [ 0.2, -0.5],
        [ 0.3, -0.5],
        [ 0.4, -0.5],
        [ 0.5, -0.5]],

       [[-0.5, -0.4],
        [-0.4, -0.4],
        [-0.3, -0.4],
        [-0.2, -0.4],
        [-0.1, -0.4],
        [-0. , -0.4],
        [ 0.1, -0.4],
        [ 0.2, -0.4],
        [ 0.3, -0.4],
        [ 0.4, -0.4],
        [ 0.5, -0.4]],

       [[-0.5, -0.3],
        [-0.4, -0.3],
        [-0.3, -0.3],
        [-0.2, -0.3],
        [-0.1, -0.3],
        [-0. , -0.3],
        [ 0.1, -0.3],
        [ 0.2, -0.3],
        [ 0.3, -0.3],
        [ 0.4, -0.3],
        [ 0.5, -0.3]],

       [[-0.5, -0.2],
        [-0.4, -0.2],
        [-0.3, -0.2],
        [-0.2, -0.2],
        [-0.1, -0.2],
        [-0. , -0.2],
        [ 0.1, -0.2],
        [ 0.2, -0.2],
        [ 0.3, -0.2],
        [ 0.4, -0.2],
        [ 0.5, -0.2]],

       [[-0.5, -0.1],
  

Задание 12.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [ ]:

a, b = np.arange(8),  np.arange(1, 9)
c = np.hstack((b%2, a%2))
np.tile(c, 4).reshape(8, 8)



array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 13.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [ ]:
a, b = np.arange(8),  np.arange(1, 9)
c = np.hstack((a%2, b%2))
np.tile(c, 4).reshape(8, 8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 14.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [ ]:
a, b = 6, 5
matrix = np.ones(a*b)

m = matrix.reshape(a, b)
np.tril(m)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Задание 15.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [ ]:
e = np.eye(a, b)
np.triu(m) - e


array([[0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Задание 16.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [ ]:
e = np.eye(a, b)


e1 = np.fliplr(e)
np.transpose(e1)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 17.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)


In [ ]:
def expected_value_np(x):
    return sum(x)/x.shape[0]

In [ ]:
def dispersion_np(x):
    e = expected_value(x)
    full_e = np.full(x.shape[0], e)
    d = ((x) - full_e)**2
    return sum(d)/x.shape[0]

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [ ]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [ ]:
def mean_square_difference_np(y1, y2):
    return sum((y1-y2)**2)/y1.shape[0]

In [ ]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [ ]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [ ]:
def mean_abs_difference_np(y1, y2):
    return sum(np.absolute(y1-y2))/y1.shape[0]

In [ ]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 20.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    return sum(y1 == y2)/y1.shape[0]

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 21.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

* Необходимо найти границы (индексы), такие, что если мы разделим какой-то из них оба вектора, то в левой части пересекающихся в $y_1$ и $y_2$ нулей будет больше, чем единиц, а в правой - наоборот. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [ ]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
def find_thresholds_np(y1, y2, debug=True):
    n = y1.shape[0]
    matching_zeros = ((y1 == y2)&(y1 == 0)).astype(int)
    matching_ones = ((y1 == y2)&(y1 == 1)).astype(int)
    res = []
    if sum(matching_ones) > sum(matching_zeros):
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

[1] [0 1 1] 1
[1 1] [1 1] 2
[1 1 0] [1] 3
[1] [0 0 0 0 1 1 1] 1
[1 1] [0 0 0 1 1 1] 2
[1 1 0] [0 0 1 1 1] 3
[1 1 0 1] [0 1 1 1] 4
[1 1 0 1 1] [1 1 1] 5
[1 1 0 1 1 0] [1 1] 6
[1 1 0 1 1 0 0] [1] 7


### Разные действия с матрицами (3 балла)

Задание 22.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно пяти** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [ ]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

d = np.concatenate((np.concatenate((data[0], data[1])), np.concatenate((data[2], data[3]))))
d1 = np.concatenate((np.concatenate((d[0], d[1])), d[3]))
c = np.concatenate((d1[0], d1[1]))
data = c.reshape(32, 1)


assert data.shape == (32, 1)

Задание 23.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя все данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256)) #8192
m2 = np.random.randint(0, 10, size=(32, 512)) #16384
W1 = np.random.randint(0, 10, size=(256, 32)) #8192
W2 = np.random.randint(0, 10, size=(512, 16))  #8192

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ !!!magic!!!
m1_NEW = np.stack((m1[0], m1[1]))         #(2, 256)

m2_NEW = np.stack((m2[0], m2[1]))         #(2, 512)

W1_NEW = np.stack((W1[0], W1[1]))         #(2, 32)

W2_NEW = np.stack((W2[0], W2[1]))         #(2, 16)


m1_m2 = np.concatenate((m1 , m2), axis=-1)
print(m1_m2.shape, "m1_m2")
m1_m2_NEW = np.hstack((m1_m2[1], m1_m2[0])) 
print(m1_m2_NEW.shape)



m1_NEW = m1_NEW.reshape(16, 32)
W2_NEW = W2_NEW.reshape(16, 2)
m1_W2 = np.concatenate((m1_NEW , W2_NEW), axis=-1)     #(16, 34)
print(m1_W2.shape, "m1_W2")

m1_W2_NEW = np.stack((m1_W2[1], m1_W2[0])) 
print(m1_W2_NEW.shape)

m2_NEW = m2_NEW.reshape(32, 32)
W1_NEW = W1_NEW.reshape(32, 2)
m2_W1 = np.concatenate((m2_NEW , W1_NEW), axis=-1)    #(32, 34)
print(m2_W1.shape, "m2_W1")

m2_W1_NEW = np.stack((m2_W1[0], m2_W1[1])) 
print(m2_W1_NEW.shape)



W22_NEW = np.concatenate((result[0], result[1]), axis=-1) 
print(W22_NEW.shape)


assert result.shape == (32, 32)

(32, 768) m1_m2
(1536,)
(16, 34) m1_W2
(2, 34)
(32, 34) m2_W1
(2, 34)


NameError: ignored

Задание 24.

Последнее испытание для юного мага матриц - приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = # Ваш код

assert ((result => 0) & (result <= 1)).all()